### ISSUE TITLE
french

### ISSUE THREAD

**Issue by ghost** [lordfriky/web-cfw-loader#13]
this language don't work

**Comment by Enovale** [comment]
I noticed... No idea what is causing it, the console says "frFR" is not defined but, it's included in the HTML file and everything

**Comment by ghost** [comment]
can you add me as collaborators to modify the french file and test to work
please

**Comment by Enovale** [comment]
...No. 

I'm pretty sure I know the problem, and fixed it. Wait for the site to update

**Comment by ghost** [comment]
It works now !! thanks ... but it need  the thanks translation !

**Comment by Enovale** [comment]
Ill do that
