### ISSUE TITLE
Payload

### ISSUE THREAD

**Issue by ghost** [lordfriky/web-cfw-loader#14]
how i can convert payloads for a web launcher like that
thanks

**Comment by Enovale** [comment]
Upload your payload and select the Print Payload Bytes checkbox, and when you press deliver payload it will print a giant array of stuff. Copy all those numbers and make sure the comma at the end is gone. Then in payloads.js do `const newPayload = new Uint8Array {<code>};` and change main.js and index.html accordingly

**Comment by ghost** [comment]
ok thanks 
can you authorise me for use your project and change for a project

**Comment by Enovale** [comment]
make a pull request

**Comment by ghost** [comment]
nope i mean fork your project and change it with my change for create a new web loader

**Comment by Enovale** [comment]
just make your changes and make a pull request, it would be annoying to have a bunch of web loaders floating around

**Comment by ghost** [comment]
because i want to create a dedicated atmosphere loader with a guide based on your work

**Comment by Enovale** [comment]
sure, I don't really care lol. Go ahead

**Comment by ghost** [comment]
ok thanks

**Comment by thomleg50** [comment]
i send you : https://github.com/thomleg50/atmosphere-!oader/invitations

**Comment by thomleg50** [comment]
https://github.com/thomleg50/atmosphere-loader/invitation

**Comment by ghost** [comment]
resolved
