### ISSUE TITLE
Triggering vulnerability

### ISSUE THREAD

**Issue by daruton** [lordfriky/web-cfw-loader#21]
I follow the tutorial correctly.
LOG:
Locate Device ID correctly.
Sends the payload as well, but at the end it remains in the following message:
"Triggering vulnerability"
And nothing happens then.

Smartphone:
Samsung J7 2016 - SM-JM700M
Android 6.0.1
Firmware: J700MUBU2BRC1
Kernel Version: 3.10.61

**Comment by Enovale** [comment]
Retry a few times, unplug and replug the switch. If it still doesn't work, try another device like a computer. Since you're using a smartphone, try NXLoader instead

**Comment by daruton** [comment]
NxLoader or Rekado are giving me two errors, with different cables.
Cable 01 - Send payload failed at offset 65536.
Cable 02 - Submiturb error.

I'm going to look for another type of OTG cable this week.
On the PC through TegraRCMGui, since I do not use any OTGs, I always have an good answer on the first try.

**Comment by Multimegamander** [comment]
Instructions unclear, uploaded porn, clicked send payload, got permabrick, plz fix

**Comment by Enovale** [comment]
if NXloader doesnt work, your usb port probably isnt XCHI, or it just doesnt like your phone. closing this issue.
