### ISSUE TITLE
Ideas for new features

### ISSUE THREAD

**Issue by Enovale** [lordfriky/web-cfw-loader#37]
I'm feeling kind of unsatisfied that I'm pretty must just merging pull requests at this point, and I want to help out with my own project more. Anyone got ideas for things that could be added to this?

**Comment by AnnsAnns** [comment]
Maybe link the needed files for each payload? ^^' Most changes that need to be done are often already done by your community (What is a great thing tbh). I think the page reached the point where nothing important has to be implemented anymore.

_There is also [this](https://github.com/tumGER/SDFilesSwitch/issues/17) when you want to ;P - Having a web-based one would be nice ;PPP_

**Comment by Enovale** [comment]
In that post are you saying like, a way to click a button and the sdfiles for each payload are ready for you?

**Comment by lorek123** [comment]
Currently managing new payloads and translations is something troublesome so here are my ideas:
- More modular and automatic payload management.
- Payload compression. Adding new payloads is not something hard, so soon payloads.js file is going to grow to a size that every file editor will have an issue to edit. We can try to split those into separate files, but using compressing libraries is something that's worth considering. This can be somehow important to mobile users, as they may want to limit transfer usage for this app. 
- Translation framework. Using OneSky for example, it's possible to put all translatable strings to an app, that will help non-technical users to translate easily app to more languages. 

Those things are ahead of our current needs, but I think they would be quite useful in the future.

**Comment by Enovale** [comment]
I could probably implement a thing where you don't even need sdfiles, as they will be installed for you, then waits for you to put your switch in rcm and runs the payload. I can also look into a translation framework and some way to modularly add payloads

**Comment by lorek123** [comment]
I will probably have some time to check the payload compression thing on the weekend. Most likely I will just add decompression to the app, and compression to converter that i wrote recently.

**Comment by AnnsAnns** [comment]
Remember to let it grab the SDfiles from the repo though - Otherwise it's going to be a Pull Request nightmare each time I update them

**Comment by lordfriky** [comment]
I was thinking in a new interface, I already have a new idea but I don't have the time for work it :/

**Comment by BeardedOranges** [comment]
I haven't tried it yet, but I am assuming that Lakka isn't supported. So maybe add support for that. I like the idea of having the SdFiles installed with it for people who just went to this website. Maybe also a link to different ways to put the switch into rcm mode for new users. Other then that, it is pretty much perfect! Nice job!

**Comment by lordfriky** [comment]
Well, a WebUSB version of shofEL2 could be written to support Lakka, or we can wait for the Linux chainloader method from CTCaer :p

**Comment by Enovale** [comment]
a while ago i looked it up, writing to USB drives (and by extension sd cards) is not possible, even with WebUSB

**Comment by k0styk** [comment]
Does it works on Raspbian?? I try with chromium, doesn't work that...
![image](https://user-images.githubusercontent.com/34454348/55585287-c1f31400-573f-11e9-8b8d-d689fb13af1d.png)

**Comment by Enovale** [comment]
This is not the proper place to ask this question but no, it only works on Windows

**Comment by AnnsAnns** [comment]
Closing the issue as this repo is currently pretty dead. If somebody has anything that they want to add, feel free to send a PR.
