### ISSUE TITLE
The french translation is horribly broken!

### ISSUE THREAD

**Issue by AnnsAnns** [lordfriky/web-cfw-loader#42]
No wonder, thomleg apparently created it lol

**Comment by Enovale** [comment]
not surprising in the slightest tbh

**Comment by AnnsAnns** [comment]
Do you think we should remove it for now? The fact that it is so broken that I got some private messages about it is kinda scary lol

**Comment by nicholemattera** [comment]
I've used this service in the past, was probably going to use it again whenever I add translations to Kosmos Updater. https://gengo.com/

**Comment by AnnsAnns** [comment]
I don't really know if that is really worth it lol

**Comment by ghost** [comment]
I can correct them
I know there mistake
Expect one for tomorrow

**Comment by AnnsAnns** [comment]
Fixed https://github.com/AtlasNX/web-cfw-loader/commit/0dec4e97723fa9d6cc5f6af6f6429a4b07ce5030
