### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by lordfriky** [lordfriky/web-cfw-loader#44]
HTTPS is needed to use WebUSB, and webcfw.sdsetup.com does not use it. If you try to launch a payload right now it doesn't even let you choose the device.

**Comment by AnnsAnns** [comment]
well spotted, ty

**Comment by noahc3** [comment]
github is in the process of assigning an https certificate, so you'll need to wait for that to happen.

**Comment by noahc3** [comment]
cert is done, https is live. http should redirect to https soon.
