### ISSUE TITLE
WEBCFW seems to be broken

### ISSUE THREAD

**Issue by AnnsAnns** [lordfriky/web-cfw-loader#53]
With previous rumors and now actual testing, we have concluded that the javascript webusb implementation of fusee-gelee seems to be broken right now.

**Comment by AnnsAnns** [comment]
Possibly fixed through https://github.com/AtlasNX/web-cfw-loader/commit/3e42e972d1fa231074b096102f1c415a0983c13f - Needs testing!

**Comment by noahc3** [comment]
Not fixed, Ubuntu 18.04, Chrome 69.0.3497.100

**Comment by lucyyyyyyy** [comment]
Worked fine for me past 2 days, all Arch packages up to date.

**Comment by noahc3** [comment]
@tylertoilet chrome version?

**Comment by lucyyyyyyy** [comment]
Chromium Version 76.0.3809.132

**Comment by noahc3** [comment]
Hmm, tested Ubuntu 18.04 with Chromium 76.0.3809.100 and Chrome 76.0.3809.132 and it doesn't work. Might be some update that caused incompatibility across certain distros.

**Comment by AnnsAnns** [comment]
Last test on Pop! Os 19.04 with latest Brave wasn't successful either.

**Comment by MysticExile** [comment]
Not working, tested on Windows 10 1903 x86-64 with Brave.

**Comment by nicholemattera** [comment]
Working with Arch with Chromium v76

Just out of curiosity the page says to add `SUBSYSTEM==\"usb\", ATTR{idVendor}==\"0955\", MODE=\"0664\", GROUP=\"plugdev\"` to `/etc/udev/rules.d/50-switch.rules`, however you shouldn't have the back slashes. Also there is no mention to adding your user to the `plugdev` group or creating the group if it doesn't exists.

**Comment by AnnsAnns** [comment]
Confirmed working again on Pop! Os 19.04 with Brave. I do understand Nichole's concern though, we definitely need to explain this better

**Comment by Trunkzeh** [comment]
Doesnt work on macOS 10.14.6 with Chrome Stable (77.0.3865.90). APX comes up; and it connects:

Requesting access to device...
Preparing to launch CTCaer_Hekate...
Connected to NVIDIA Corp. APX

However thats it. No payload is pushed. Screen on Switch remains blank.

**Comment by AnnsAnns** [comment]
macOS might possibly be fixed through #59.
Windows seems to sometimes work (Heard about Edge Chromium supporting it correctly)
Linux works fully again (with the tweak).
