### ISSUE TITLE
Outdated payload(s?)

### ISSUE THREAD

**Issue by shny-scott** [lordfriky/web-cfw-loader#54]
It seems like Hekate 4.6 is still being used, I haven't tested fusee or reinx as I don't use those (just use hekate for launching Android). Hekate that old can't boot newer firmwares, and that fusee definitely won't work with latest atmosphere.

**Comment by AnnsAnns** [comment]
Hm, this might actually be the reason it isn't working right now. Will be updating the payloads shortly :)

**Comment by AnnsAnns** [comment]
Should be fixed now (https://github.com/AtlasNX/web-cfw-loader/commit/3e42e972d1fa231074b096102f1c415a0983c13f)

**Comment by noahc3** [comment]
Hekate 4.6 will chainload latest Hekate from the SD card automatically anyways.
