### ISSUE TITLE
Outdated Hekate

### ISSUE THREAD

**Issue by shny-scott** [lordfriky/web-cfw-loader#56]
Latest hekate (5.0.2) is updated to support 9.0.0, 5.0.1 (the version the injector uses) only supports up to 8.1.0.

**Comment by friedkeenan** [comment]
Hekate should just chainload the `bootloader/update.bin` payload if it's a newer version, so I don't think it's *necessary* to update it

**Comment by AnnsAnns** [comment]
Updating this is a bit annoying right now, I'm thinking about automating it sooner or later though :)

And @friedkeenan is correct even if it means that it's somewhat dirty.

**Comment by ThatNerdyPikachu** [comment]
meh. i'll make a thing, would save you some time.

~~*h e l l o  s c o t t ,  f r o m  t h e  h y p e r s p a c e*~~

**Comment by Yaroster** [comment]
Are you still planning on updating Hekate ?

**Comment by lordfriky** [comment]
Since updating payloads is a little bit tedious, I started to work on a alternative, where payloads don't need to be converted to work with this. I'll open another issue explaining it showing my progress of it. But now, this issue can be closed with #62

**Comment by 3x3cut0r** [comment]
could somebody update hekate to latest 5.5.4?

**Comment by Yaroster** [comment]
I second this, we need an update please :)

**Comment by lordfriky** [comment]
I'm sorry guys, I've been very busy lately and sometimes I don't have much time to update the payloads, but since rn I have like 30 minutes of free time I'll do the updates asap

**Comment by lordfriky** [comment]
Done! I did not update fusee-primary since it was last updated on 0.17.0 so the one that is there should work fine

I'll keep this issue open since pretty much everytime I forgot to update the payloads, so if you can let me know here that the payloads are outdated (or in Twitter, feel free to send a DM) that would be great :b

**Comment by Yaroster** [comment]
Thank you !!! :))))))

**Comment by lordfriky** [comment]
Finally fusee-primary was updated in the latest [Atmosphère release](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.19.2),  so I'll update it asap

**Comment by 3x3cut0r** [comment]
Hekate 5.5.6 and Atmosphere 0.19.3 has been released. could you again update?
is there no possibility to automate the update process somehow? with a git-action for example?
then we don't need to ask every time?

thank you!

**Comment by Enovale** [comment]
You could probably automate it in a github action yes, especially using linux tools.

**Comment by Yaroster** [comment]
*https://github.com/actions/github-script
<https://github.com/actions/github-script>*

>

**Comment by lordfriky** [comment]
Thank you so much guys, I'll take a look at it

In the meantime, I'll update both payloads asap

**Comment by 3x3cut0r** [comment]
Hekate 5.5.7 and Atmosphere 0.19.4 has been released.
Any Updates for the git-action yet?

**Comment by lordfriky** [comment]
Sorry, I haven't worked on the git action yet :c
And I'am also in a trip with my family right now, but I'll check if I can at least update the payloads with codespaces on an iPad (I didn't bring my computer with me)

**Comment by lordfriky** [comment]
This shouldn't be an issue anymore :)
