### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by ElCosmoXD** [lordfriky/web-cfw-loader#57]
The page is not fully translated, here is a snippet of the translated page code to make it easier to update ;)
______________________________________________________________________________________________________
![Captura 1](https://user-images.githubusercontent.com/37759352/65253367-e87bf000-dad0-11e9-8c1d-febaf65b666d.PNG)

The code in spanish: 
`<p>En Linux, tu puedes obtener el error de 'Acceso Denegado' o 'Dispositivo no compatible' En el dialogo cuanto conectas! Tu puedes intentar crear un archivo con: <code>/etc/udev/rules.d/50-switch.rules</code>Con Los siguientes contenidos:<br><code>SUBSYSTEM=="usb", ATTR{idVendor}=="0955", MODE="0664", GROUP="plugdev"</code> y despues agrega tu mismo a el grupo "plugdev" escribiendo: <code>sudo usermod -a -G plugdev YOUR_NAME</code></p>`
______________________________________________________________________________________________________
![Captura 2](https://user-images.githubusercontent.com/37759352/65254074-17df2c80-dad2-11e9-922c-501ab8038942.PNG)

The code in spanish: 
`<p id="warningTested">Esto ha sido probado y aparentemente funciona en: Linux, OSX, Android (Sin Root) y Chromebooks. Su experiencia puede ser diferente.</p>`
______________________________________________________________________________________________________
![Captura 3](https://user-images.githubusercontent.com/37759352/65254546-da2ed380-dad2-11e9-9a1a-56513cbd5034.PNG)

The code in spanish:
```
<p><strong id="labelInstructions">Instrucciones:</strong></p>
<ul>
          <li id="liRCM">Pon tu switch en RCM, y conectalo en tu dispositivo.</li>
          <li id="liSelect">Selecciona entre el payload, de ejemplo o sube uno como "Kosmos".</li>
          <li id="liPress">Presiona 'Lanzar Payload!'</li>
          <li id="liAPX">En la pantalla que aparece, seleccione 'APX' y presione 'Conectar'.</li>
          <li id="liLaunch">Si todo va bien, el payload sera lanzado!</li>
</ul>
```
______________________________________________________________________________________________________
![Captura 4](https://user-images.githubusercontent.com/37759352/65254666-05192780-dad3-11e9-8f56-a63f65217e38.PNG)

The code in spanish:
`<p>Guia de hackeos: <strong><a href="https://guide.teamatlasnx.com">AQUI</a></strong></p>`
______________________________________________________________________________________________________
![Captura 5](https://user-images.githubusercontent.com/37759352/65255047-91c3e580-dad3-11e9-9499-194ab0e892b5.PNG)
The code in spanish: 
`<p id="labelContribute">Si tu quisieras ayudar con una traduccion o subiendo/añadiendo un payload, mira <a href="https://github.com/AtlasNX/web-cfw-loader/blob/master/CONTRIBUTING.md">esto</a>.</p>`
______________________________________________________________________________________________________
![Captura 7](https://user-images.githubusercontent.com/37759352/65255410-35ad9100-dad4-11e9-8c69-af08cea05fb7.PNG)

The code in spanish: 
```
<div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
        <h1 id="h1SetupDelivery">Lanzamiento del Payload</h1>

        <form id="mainForm">
          <div class="row">
            <div class="col-xs-6">
              <h4 id="h4SelectPayload">Selecciona el Payload:</h4>
            </div>

            <div class="col-xs-6">
              <select class="pull-right" id="payloadSelect" onchange="onSelectChange()">
                <option value="CTCaer_Hekate" id="optionCTCaerHekate">Hekate</option>
                <option value="uploaded" id="optionUpload">Lanzar Payload</option>
              </select>
            </div>
          </div>

          <div class="row" id="uploadContainer" style="display: none">
            <div class="col-xs-12">
              <input style="float: right" type="file" id="payloadUpload" accept=".bin">
            </div>
          </div>
          <div class="row divider-line"></div>

          <div class="row margin-top-md">
            <div class="col-xs-10">
              <h4 id="h4GetByteArray">Obtener el payload byte array</h4>
            </div>
            <div class="col-xs-2">
              <input class="pull-right" type="checkbox" name="shouldDebug" id="shouldDebug">
            </div>
          </div>
          <div class="row divider-line"></div>
        </form>
```
______________________________________________________________________________________________________

PD: Sorry for not adding the "es_ES.js" but I didn't read the contribution.md :(

**Comment by AnnsAnns** [comment]
No worries, thank you so much for your PR/Issue

**Comment by ElCosmoXD** [comment]
:D

**Comment by AnnsAnns** [comment]
(The translation hasn't been updated yet, wait for somebody to commit it before closing this issue lol)

**Comment by ElCosmoXD** [comment]
xD

**Comment by ElCosmoXD** [comment]
ok, i'm waiting :)

**Comment by ElCosmoXD** [comment]
@tumGER One question, how do Payloads convert to Hexadecimal for javascript? Because I would like to carry payloads for web pages like this.

**Comment by AnnsAnns** [comment]
It's quite simple - Upload a payload, check the "don't 'sploit" button and then copy the console's binary output to the payload.js variable for hekate (which is the hacky problem with this)

**Comment by ElCosmoXD** [comment]
wow, is very simple, Thank You.

**Comment by lordfriky** [comment]
The full spanish translation is there, I actually made it more than a year ago, but it seems like something broke the translation script, since the rest of the languages aren't properly working neither. :b

I'll try to track down the bug this week and fix it.

**Comment by lordfriky** [comment]
Wow, this issue was made 4 months ago and no one complained about other languages to be broken too. Seems like no one is carying about web-cfw-loader now or not a lot of people knows about this tool or why it is such a big deal for Chromebook users like myself. :c

**Comment by ElCosmoXD** [comment]
i forked this project for fix the broken languages. And i can see the error. For now the error is what the files like es-MX.js don't have all the traduction. But I am working to solve it. :D

**Comment by lordfriky** [comment]
The repo contains a full (outdated) spanish translation, there's no need to modify the file to fix this. Also, I made a PR to fix this some minutes ago.

**Comment by ElCosmoXD** [comment]
I gonna check the possible bugs, and i try to fix this.

**Comment by AnnsAnns** [comment]
> Wow, this issue was made 4 months ago and no one complained about other languages to be broken too. Seems like no one is carying about web-cfw-loader now or not a lot of people knows about this tool or why it is such a big deal for Chromebook users like myself. :c 

It's quite simple, most people just use the standard language and keeping languages updated is a huge pita.

**Comment by ElCosmoXD** [comment]
Anyway, the error is already fixed.
