### ISSUE TITLE
Hangs on "Preparing to launch payload" on Linux

### ISSUE THREAD

**Issue by neomoth** [lordfriky/web-cfw-loader#70]
When attempting to use the payload injector on my Linux machine the console output hangs at "Preparing to launch payload" at which point nothing will happen whatsoever. What's strange is this seems to happen on any payload injector website on my machine, and the fusee-interfacee-tk injector just fails outright, although doing any of this on windows with tegrarcmgui just works. Is this an issue with the method used to inject the payload or a problem with my linux installation?

**Comment by lordfriky** [comment]
(Sorry for the late answer)
Hmmm, is there any error showing through the chrome console?

**Comment by einekratzekatze** [comment]
Had the same Problem. The Console says: `main.js:131 Uncaught (in promise) DOMException: Failed to execute 'open' on 'USBDevice': Access denied.`
Not sure how to fix it on fedora

**Comment by Wiilf** [comment]
that is the method that opens the connection and establishes the payload logic. 
Check to make sure WebUSB is enabled:

`
if (!navigator.usb) {
  alert('Web USB is not enabled.');
}
`

This is how we deal with Firefox, and then we just send the log message.

**Comment by lordfriky** [comment]
A check for web usb has been added, thanks!

**Comment by Wiilf** [comment]
There is still a lot missing that we implemented a year ago, like device listing, icons and extended device info.

Sent from my iPhone

On May 9, 2024, at 1:20 AM, Lord Friky ***@***.***> wrote:

﻿

A check for web usb has been added, thanks!
